config/routes.rb
Rails.application.routes.draw do

  root  'welcome#home'

  get 'press', to: 'welcome#press'

  get 'rules', to: 'welcome#rules'

  get 'wholesale', to: 'welcome#wholesale'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController


  def home

  end

  def press

  end


  def rules


  end


  def wholesale

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_googleanalytics.html.erb
<% if Rails.env == "production" %>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-73948334-1', 'auto');
  ga('send', 'pageview');

</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Battle Of The Bands</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="google-site-verification" content="_KqVj6yt4a09AnQhA3PypGSnBUKW_C10JrH3Pvhu4R8" />

<%= render 'layouts/googleanalytics' %>

</head>
<body>
  <div class="title">
    <h1> Battle of the Bands </h1>
    <p>A card game about record deals and creative differences</p>
    <p>Kickstarter badge on the left</p>
  </div>

<%= yield %>

<%= render 'footer' %>

</body>
</html>

app/views/welcome/_footer.html.erb
<div class="footer">
    <nav class="row" role="navigation">
      <p> Copy Battle of the Bands 2016 </p>
      <ul>
       <li><%= link_to "Instructions", rules_path %></li>
       <li><%= link_to "Press Kit", press_path %></li>
       <li><%= link_to "Wholesale", wholesale_path %></li>
      </ul>
    </nav>
</div>

app/views/welcome/_lineup.html.erb
<div class='container-fluid'>
  <div class="row">
    <div class="col-xs-3">
      <div class="lineup">
      <% image_tag("Hype002.png") %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/_mailchimp.html.erb
<!-- Begin MailChimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/slim-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>
<div id="mc_embed_signup">
<form action="//battleofthebandscardgame.us12.list-manage.com/subscribe/post?u=400c29ba792d83066bd1fbac4&amp;id=79faaf2100" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">

	<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_400c29ba792d83066bd1fbac4_79faaf2100" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->

app/views/welcome/_navbar.html.erb
<nav class="navbar navbar-inverse" data-spy="affix" data-offset-top="197">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#TheGame">The Game <span class="sr-only">(current)</span></a></li>
        <li><a href="#ContactUs">Contact Us</a></li>
        <li><a href="#FAQ">FAQ</a></li>
        <li><a href="#Connect">Connect</a></li>

       </ul>

      <ul class="nav navbar-nav navbar-right">
          <li><a href="#Purchase">Purchase</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/welcome/_subscribe.html.erb
<div class="container-fluid subscribe">
  <div class="row">
    <div class="col-xs-offset-4 col-xs-4">
      <a id="Connect"></a>
      <%= render 'mailchimp' %>
    </div>
  </div>
</div>

app/views/welcome/home.html.erb
<%= render 'navbar' %>

<%= render 'lineup' %>

<div class="section">
  <h2><a id="TheGame">The Game</a></h2>
</div>

<div class="section">
  <h2><a id="Purchase">Purchase</a></h2>
</div>

<div class="section">
  <h2><a id="ContactUs">Contact Us</a></h2>
</div>

<div class="section">
  <h2><a id="FAQ">FAQ</a></h2>
</div>

<%= render 'subscribe' %>

app/views/welcome/press.html.erb
<h1> Press </h1>


<button>Toggle</button>

<p>This is a paragraph with little content.</p>
<p>This is another small paragraph.</p>



<div id="animate">Animate</div>


<script>
  var a = $("#animate");
  a.slideUp(1000);
</script>

app/views/welcome/rules.html.erb
<h1> Rules </h1>


<div class= "container-fluid">
  <div class= "row testing">
     <div class="col-xs-offset-3 col-xs-6 col-sm-offset-0 col-sm-6 col-md-4 col-lg-12">
       <div class="row">
         <div class="col-lg-1 col-lg-offset-3">
           <p>image</p>
         </div>
         <div class="col-lg-5">
           <h1>Headline</h1>
          <p> Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap </p>
         </div>
         </div>
    </div>
  <div class="col-xs-offset-3 col-xs-6 col-sm-offset-0 col-sm-6 col-md-4 col-lg-3">
       <h1>Headline</h1>
  <p> Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap </p>
    </div>

     <div class="col-xs-offset-3 col-xs-6 col-sm-offset-0 col-sm-6 col-md-4 col-lg-3">
       <h1>Headline</h1>
  <p> Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap </p>
    </div>

     <div class="col-xs-offset-3 col-xs-6 col-sm-offset-0 col-sm-6 col-md-4 col-lg-3">
       <h1>Headline</h1>
  <p> Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap </p>
    </div>
     <div class="col-xs-offset-3 col-xs-6 col-sm-offset-0 col-sm-6 col-md-4 col-lg-3">
       <h1>Headline</h1>
  <p> Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap </p>
    </div>

     <div class="col-xs-offset-3 col-xs-6 col-sm-offset-0 col-sm-6 col-md-4 col-lg-3">
       <h1>Headline</h1>
  <p> Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap Testing Bootstrap </p>
    </div>
   </div>
</div>

app/views/welcome/wholesale.html.erb
<h1> Wholesale </h1>